In [3]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
#importing dataset
main_data= pd.read_csv('dataset.csv')
main_data.head()


user_id  Mode  Expected_Time  Actual_Time  Correct_Answers  Next_Mode
0   1001.0     0            300            1                0          0
1   1002.0     0            300            1                1          0
2   1003.0     0            300            1                2          0
3   1004.0     0            300            1                3          0
4   1005.0     0            300            1                4          1

In [9]:
del main_data['user_id']

#seperate x and y data
X=['Mode','Expected_Time','Actual_Time','Correct_Answers']
y=['Next_Mode']

In [10]:
X = main_data.iloc[:, :-1].values
y = main_data['Next_Mode']

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3,random_state=3, stratify=y)

In [12]:
#training the model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [13]:
#predicting with test set
y_pred = knn.predict(X_test)
y_pred

array([1, 0, 0, ..., 1, 2, 0], dtype=int64)

In [150]:
pd.DataFrame(y_test).to_csv("file1.csv")
pd.DataFrame(y_pred).to_csv("file2.csv")

THE TEST TRAIN SPLIT OF MAIN DATA WAS SUCCESFULL AND THE ANSWERS WHERE CORRECT

LET US CHECK THE MODEL ACCURACY

In [163]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import log_loss

results = confusion_matrix(y_test, y_pred)
print ('Confusion Matrix :')
print(results)
print ('Accuracy Score is',accuracy_score(y_test, y_pred))
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Confusion Matrix :
[[3134   56   57]
 [  56 3288  104]
 [  64  136 1299]]
Accuracy Score is 0.9422748352453014
Classification Report : 
              precision    recall  f1-score   support

           0       0.96      0.97      0.96      3247
           1       0.94      0.95      0.95      3448
           2       0.89      0.87      0.88      1499

    accuracy                           0.94      8194
   macro avg       0.93      0.93      0.93      8194
weighted avg       0.94      0.94      0.94      8194



creating a function to check the prediction